Repository aminespinoza10/App-de-Vecinos, pull requests merged in 2025-01, with the labels that each got.

#7 Amin/1
  docs/assets/database.png
  docs/database.md
Labels: documentation

#16 Dockerfile added
  AppVecinos.API/Dockerfile
Labels: enhancement

#23 Model parameters in endpoints renamed
  AppVecinos.API/Program.cs
Labels: bug

#24 CD process for Vecinos API created
  .github/workflows/APIdeploy.yml
Labels: enhancement

#28 Added Semantic Versions to the Docker Image
  .github/workflows/APIdeploy.yml
Labels: enhancement
